In [1]:
import pandas as pd
import numpy as np

## Customer Dataset

In [2]:
df_customers = pd.read_csv("../01_Raw_Data/customers.csv")

In [3]:
df_customers.shape

(50000, 7)

In [4]:
df_customers.head()

,customer_id,first_name,last_name,email,city,credit_score,created_at
0,CUSXAJI0Y6DPBHS,Neha,Joshi,neha.joshi1@sbi.co.in,Hyderabad,327,2025-04-17
1,CUSHXTHV3A3ZMF8,Rahul,Singh,rahul.singh2@sbi.co.in,Chennai,644,2020-02-23
2,CUSDD4V30T9NT3W,Vikram,Pandey,vikram.pandey3@sbi.co.in,Chennai,670,2025-06-22
3,CUSGCX1945NQ4FM,Sneha,Saxena,sneha.saxena4@sbi.co.in,Kolkata,573,2019-10-20
4,CUSVG0FN9XUY41I,Sneha,Kapoor,sneha.kapoor5@sbi.co.in,Gurugram,332,2022-07-16

In [5]:
df_customers.columns

Index(['customer_id', 'first_name', 'last_name', 'email', 'city',
       'credit_score', 'created_at'],
      dtype='object')

In [6]:
df_customers.describe(include="all")

,customer_id,first_name,last_name,email,city,credit_score,created_at
count,50000,50000,50000,50000,50000,50000.000000,50000
unique,50000,20,20,50000,15,NaN,2557
top,CUSXAJI0Y6DPBHS,Nikhil,Kumar,neha.joshi1@sbi.co.in,Delhi,NaN,2022-06-10
freq,1,2594,2566,1,3453,NaN,35
mean,NaN,NaN,NaN,NaN,NaN,574.490520,NaN
std,NaN,NaN,NaN,NaN,NaN,158.692145,NaN
min,NaN,NaN,NaN,NaN,NaN,300.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,437.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,575.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,712.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,850.000000,NaN

In [7]:
df_customers.isnull().sum()

customer_id     0
first_name      0
last_name       0
email           0
city            0
credit_score    0
created_at      0
dtype: int64

In [8]:
df_customers.duplicated().sum()

np.int64(0)

In [9]:
df_customers.nunique()

customer_id     50000
first_name         20
last_name          20
email           50000
city               15
credit_score      551
created_at       2557
dtype: int64

In [10]:
df_customers.dtypes

customer_id     object
first_name      object
last_name       object
email           object
city            object
credit_score     int64
created_at      object
dtype: object

### Observation - Customer Dataset

- The dataset contains 50,000 customer records and 7 columns.
- No missing values or duplicate records were found.
- Each customer has a unique customer_id and email.
- The dataset contains customers from 15 different cities.
- credit_score is stored as an integer, while created_at is stored as an object and should be converted to datetime during data cleaning.

## Accounts Dataset

In [11]:
df_accounts = pd.read_csv("../01_Raw_Data/accounts.csv")

In [12]:
df_accounts.shape

(75000, 5)

In [13]:
df_accounts.head()

        account_id      customer_id account_type  balance_inr   open_date
0  ACCOD48PUCAEHKH  CUSAEOACKBH8CK6     Checking    182700.46  2021-03-27
1  ACCU2DMTSOYD5R6  CUSKI0ABUBGCLFD      Savings     57886.71  2019-10-21
2  ACCXFI6TF26FL9B  CUSWXG0ESCUG77M     Business     68774.44  2019-02-15
3  ACCJ6SUS4ZI6BRT  CUSUTT52LK3TW0J     Business     67015.68  2021-10-30
4  ACCNP7JE3AQW8TG  CUSNUWQT2EXWNSC      Savings     67265.67  2023-12-05

In [14]:
df_accounts.columns

Index(['account_id', 'customer_id', 'account_type', 'balance_inr',
       'open_date'],
      dtype='object')

In [15]:
df_accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75000 entries, 0 to 74999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   account_id    75000 non-null  object
 1   customer_id   75000 non-null  object
 2   account_type  75000 non-null  object
 3   balance_inr   75000 non-null  float64
 4   open_date     75000 non-null  object
dtypes: float64(1), object(4)
memory usage: 2.9+ MB

In [16]:
df_accounts.describe(include="all")

,account_id,customer_id,account_type,balance_inr,open_date
count,75000,75000,75000,75000.000000,75000
unique,75000,38838,3,NaN,2557
top,ACCOD48PUCAEHKH,CUSKK7I7WDRTTNA,Checking,NaN,2024-09-22
freq,1,8,25090,NaN,53
mean,NaN,NaN,NaN,100181.721881,NaN
std,NaN,NaN,NaN,57637.062728,NaN
min,NaN,NaN,NaN,13.200000,NaN
25%,NaN,NaN,NaN,50406.112500,NaN
50%,NaN,NaN,NaN,100316.825000,NaN
75%,NaN,NaN,NaN,149973.740000,NaN
max,NaN,NaN,NaN,199994.580000,NaN

In [17]:
df_accounts.isnull().sum()

account_id      0
customer_id     0
account_type    0
balance_inr     0
open_date       0
dtype: int64

In [18]:
df_accounts.duplicated().sum()

np.int64(0)

In [19]:
df_accounts.nunique()

account_id      75000
customer_id     38838
account_type        3
balance_inr     74846
open_date        2557
dtype: int64

In [20]:
df_accounts.dtypes

account_id       object
customer_id      object
account_type     object
balance_inr     float64
open_date        object
dtype: object

### Observation - Accounts Dataset
- The dataset contains 75,000 account records and 5 columns.
- No missing values or duplicate records were found.
- One customer can have multiple bank accounts.
- The dataset contains 3 account types: Savings, Checking, and Business.
- balance_inr is stored as a numeric column, while open_date should be converted to datetime during data cleaning.

## Transactions Dataset

In [21]:
df_transactions = pd.read_csv("../01_Raw_Data/transactions.csv")

In [22]:
df_transactions.shape

(1000000, 5)

In [23]:
df_transactions.head()

,transaction_id,account_id,merchant_id,amount_inr,transaction_date
0,TXN00005HFWN2XNY3,ACCP1YZO9D6NWHS,MER1ECHZUV9E1WF,9239.92,1/14/2022 4:58
1,TXN00009897MR3AF0,ACC39NBWQ11B0YW,MERBTO90OBMKTWM,8261.44,2/20/2021 0:12
2,TXN0002DXC6LENBZN,ACCVEP6O0JTRPHJ,MERI68JP0JLHMNF,127.38,6/2/2024 11:20
3,TXN0003B7W0PHYMBL,ACC9DAR8N097DNX,MERN7Z2NR7VK3E6,501.59,3/8/2020 22:36
4,TXN0003LEFVFA0V95,ACCNULMR5ZNMBK9,MER5284SUXHD16Q,1535.35,9/1/2024 6:49

In [24]:
df_transactions.columns

Index(['transaction_id', 'account_id', 'merchant_id', 'amount_inr',
       'transaction_date'],
      dtype='object')

In [25]:
df_transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 5 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   transaction_id    1000000 non-null  object
 1   account_id        1000000 non-null  object
 2   merchant_id       1000000 non-null  object
 3   amount_inr        1000000 non-null  float64
 4   transaction_date  1000000 non-null  object
dtypes: float64(1), object(4)
memory usage: 38.1+ MB

In [26]:
df_transactions.describe(include="all")

,transaction_id,account_id,merchant_id,amount_inr,transaction_date
count,1000000,1000000,1000000,1000000.000000,1000000
unique,1000000,75000,5000,NaN,875380
top,TXN00005HFWN2XNY3,ACCB1WVS7GK7C9V,MER6BHDTKK0NKCT,NaN,7/28/2023 14:29
freq,1,33,252,NaN,6
mean,NaN,NaN,NaN,5001.164534,NaN
std,NaN,NaN,NaN,2887.405435,NaN
min,NaN,NaN,NaN,1.020000,NaN
25%,NaN,NaN,NaN,2502.800000,NaN
50%,NaN,NaN,NaN,5000.725000,NaN
75%,NaN,NaN,NaN,7503.937500,NaN
max,NaN,NaN,NaN,9999.980000,NaN

In [27]:
df_transactions.isnull().sum()

transaction_id      0
account_id          0
merchant_id         0
amount_inr          0
transaction_date    0
dtype: int64

In [28]:
df_transactions.duplicated().sum()

np.int64(0)

In [29]:
df_transactions.nunique()

transaction_id      1000000
account_id            75000
merchant_id            5000
amount_inr           631880
transaction_date     875380
dtype: int64

In [30]:
df_transactions.dtypes

transaction_id       object
account_id           object
merchant_id          object
amount_inr          float64
transaction_date     object
dtype: object

### Observation- Transactions Dataset
- The dataset contains 1,000,000 transaction records and 5 columns.
- No missing values or duplicate records were found.
- This is the largest dataset in the project.
- Transactions are linked to accounts and merchants using account_id and merchant_id.
- amount_inr is stored as a numeric column, while transaction_date should be converted to datetime during data cleaning.

## Cards Dataset

In [31]:
df_cards = pd.read_csv("../01_Raw_Data/cards.csv")

In [32]:
df_cards.shape

(100000, 4)

In [33]:
df_cards.head()

           card_id       account_id card_type expiration_date
0  CRD9DMMMTJDQT3V  ACC32AXBRYBVYAR     Debit      2032-02-07
1  CRD94590WYP462W  ACC2WKDTIPM83SK    Credit      2030-03-14
2  CRDB79THXNR6SGQ  ACCPZTJ2AUNVBRX    Credit      2026-12-17
3  CRDG81QQ58532B9  ACCV78E7JOA2O54     Debit      2029-10-21
4  CRD7RTUV3VVPJ60  ACCS8PHD7QLVC4L    Credit      2028-02-05

In [34]:
df_cards.columns

Index(['card_id', 'account_id', 'card_type', 'expiration_date'], dtype='object')

In [35]:
df_cards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   card_id          100000 non-null  object
 1   account_id       100000 non-null  object
 2   card_type        100000 non-null  object
 3   expiration_date  100000 non-null  object
dtypes: object(4)
memory usage: 3.1+ MB

In [36]:
df_cards.describe(include="all")

                card_id       account_id card_type expiration_date
count            100000           100000    100000          100000
unique           100000            55198         2            2922
top     CRD9DMMMTJDQT3V  ACCTZNVCMI7XDC9     Debit      2030-02-22
freq                  1                8     50281              56

In [37]:
df_cards.isnull().sum()

card_id            0
account_id         0
card_type          0
expiration_date    0
dtype: int64

In [38]:
df_cards.duplicated().sum()

np.int64(0)

In [39]:
df_cards.nunique()

card_id            100000
account_id          55198
card_type               2
expiration_date      2922
dtype: int64

In [40]:
df_cards.dtypes

card_id            object
account_id         object
card_type          object
expiration_date    object
dtype: object

### Observation- Cards Dataset

- The dataset contains 100,000 card records and 4 columns.
- No missing values or duplicate records were found.
- One account can have multiple cards.
- The dataset contains Debit and Credit cards.
- expiration_date should be converted to datetime during data cleaning.

## Loans Dataset

In [41]:
df_loans = pd.read_csv("../01_Raw_Data/loans.csv")

In [42]:
df_loans.shape

(30000, 5)

In [43]:
df_loans.head()

           loan_id      customer_id  loan_amount  interest_rate  start_date
0  LONVIJLFE0FQERD  CUS0VWWKGL3C2ET      7939.97           8.16  2024-05-05
1  LONHREM3GBFRZCN  CUSK3SW6KH12S96    176269.07           3.84  2022-12-12
2  LONRVF09SWTR92A  CUS7D2AZQQGCDHI    193167.37          10.97  2024-06-01
3  LONVIO8NY2TPJ97  CUSKF0P22H7PUEM     15623.54          13.35  2020-02-21
4  LON8MO4Z8F2MY71  CUS4KVHY58PGUXF     50695.04           7.37  2019-04-25

In [44]:
df_loans.columns

Index(['loan_id', 'customer_id', 'loan_amount', 'interest_rate', 'start_date'], dtype='object')

In [45]:
df_loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   loan_id        30000 non-null  object
 1   customer_id    30000 non-null  object
 2   loan_amount    30000 non-null  float64
 3   interest_rate  30000 non-null  float64
 4   start_date     30000 non-null  object
dtypes: float64(2), object(3)
memory usage: 1.1+ MB

In [46]:
df_loans.describe(include="all")

,loan_id,customer_id,loan_amount,interest_rate,start_date
count,30000,30000,30000.000000,30000.000000,30000
unique,30000,22586,NaN,NaN,2557
top,LONVIJLFE0FQERD,CUSA277NSK878WQ,NaN,NaN,2020-01-28
freq,1,6,NaN,NaN,26
mean,NaN,NaN,150089.016603,8.507418,NaN
std,NaN,NaN,86370.873092,3.752818,NaN
min,NaN,NaN,1010.160000,2.000000,NaN
25%,NaN,NaN,75500.137500,5.270000,NaN
50%,NaN,NaN,150571.300000,8.510000,NaN
75%,NaN,NaN,224719.092500,11.770000,NaN
max,NaN,NaN,299975.470000,15.000000,NaN

In [47]:
df_loans.isnull().sum()

loan_id          0
customer_id      0
loan_amount      0
interest_rate    0
start_date       0
dtype: int64

In [48]:
df_loans.duplicated().sum()

np.int64(0)

In [49]:
df_loans.nunique()

loan_id          30000
customer_id      22586
loan_amount      29985
interest_rate     1301
start_date        2557
dtype: int64

In [50]:
df_loans.dtypes

loan_id           object
customer_id       object
loan_amount      float64
interest_rate    float64
start_date        object
dtype: object

### Observation- Loans Dataset

- The dataset contains 30,000 loan records and 5 columns.
- No missing values or duplicate records were found.
- One customer can have multiple loans.
- loan_amount and interest_rate are stored in numeric format.
- start_date should be converted to datetime during data cleaning.

## Branches Dataset

In [51]:
df_branches = pd.read_csv("../01_Raw_Data/branches.csv")

In [52]:
df_branches.shape

(500, 3)

In [53]:
df_branches.head()

         branch_id          branch_name  manager_name
0  BRNJITQ446NVY1P  SBI Connaught Place  Rahul Sharma
1  BRNVXROZ3RRD54H           SBI Bandra    Amit Verma
2  BRN6IUCH832B5CG          SBI MG Road   Priya Patel
3  BRNQKSE7WVBUGTJ      SBI Park Street    Neha Singh
4  BRNZDKYMIYBCVIN       SBI Anna Nagar   Arjun Gupta

In [54]:
df_branches.columns

Index(['branch_id', 'branch_name', 'manager_name'], dtype='object')

In [55]:
df_branches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   branch_id     500 non-null    object
 1   branch_name   500 non-null    object
 2   manager_name  500 non-null    object
dtypes: object(3)
memory usage: 11.8+ KB

In [56]:
df_branches.describe(include="all")

              branch_id          branch_name  manager_name
count               500                  500           500
unique              500                   15            15
top     BRNJITQ446NVY1P  SBI Connaught Place  Rahul Sharma
freq                  1                   34            34

In [57]:
df_branches.isnull().sum()

branch_id       0
branch_name     0
manager_name    0
dtype: int64

In [58]:
df_branches.duplicated().sum()

np.int64(0)

In [59]:
df_branches.nunique()

branch_id       500
branch_name      15
manager_name     15
dtype: int64

In [60]:
df_branches.dtypes

branch_id       object
branch_name     object
manager_name    object
dtype: object

### Observation- Branches Dataset

- The dataset contains 500 branch records and 3 columns.
- No missing values or duplicate records were found.
- Each branch has a unique branch_id.
- The dataset contains 15 branch names and their respective managers.

## Merchants Dataset

In [61]:
df_merchants = pd.read_csv("../01_Raw_Data/merchants.csv")

In [62]:
df_merchants.shape

(5000, 3)

In [63]:
df_merchants.head()

       merchant_id     merchant_name       city
0  MERU9JCGLS9MNLI   Reliance Retail     Mumbai
1  MER43QNBEL8JWEW             DMart      Delhi
2  MER3N5P7AWGR7U5        Big Bazaar  Bengaluru
3  MERLXSBZNU5LYTU  Reliance Digital    Chennai
4  MERT7OA8XC77HJ1             Croma  Hyderabad

In [64]:
df_merchants.columns

Index(['merchant_id', 'merchant_name', 'city'], dtype='object')

In [65]:
df_merchants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   merchant_id    5000 non-null   object
 1   merchant_name  5000 non-null   object
 2   city           5000 non-null   object
dtypes: object(3)
memory usage: 117.3+ KB

In [66]:
df_merchants.describe(include="all")

            merchant_id    merchant_name    city
count              5000             5000    5000
unique             5000               15      15
top     MERU9JCGLS9MNLI  Reliance Retail  Mumbai
freq                  1              334     334

In [67]:
df_merchants.isnull().sum()

merchant_id      0
merchant_name    0
city             0
dtype: int64

In [68]:
df_merchants.duplicated().sum()

np.int64(0)

In [69]:
df_merchants.nunique()

merchant_id      5000
merchant_name      15
city               15
dtype: int64

In [70]:
df_merchants.dtypes

merchant_id      object
merchant_name    object
city             object
dtype: object

### Observation- Merchants Dataset


- The dataset contains 5,000 merchant records and 3 columns.
- No missing values or duplicate records were found.
- Each merchant has a unique merchant_id.
- The dataset contains 15 merchant names across 15 cities.